# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import feature_pb2 as feature__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='face',
  syntax='proto3',
  serialized_options=b'\370\001\001',
  serialized_pb=b'\n\rexample.proto\x12\x04\x66\x61\x63\x65\x1a\rfeature.proto\"+\n\x07\x45xample\x12 \n\x08\x66\x65\x61tures\x18\x01 \x01(\x0b\x32\x0e.face.Features\"]\n\x0fSequenceExample\x12\x1f\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\x0e.face.Features\x12)\n\rfeature_lists\x18\x02 \x01(\x0b\x32\x12.face.FeatureListsB\x03\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[feature__pb2.DESCRIPTOR, ])




_EXAMPLE = _descriptor.Descriptor(
  name='Example',
  full_name='face.Example',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='features', full_name='face.Example.features', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=81,
)


_SEQUENCEEXAMPLE = _descriptor.Descriptor(
  name='SequenceExample',
  full_name='face.SequenceExample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='face.SequenceExample.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_lists', full_name='face.SequenceExample.feature_lists', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=176,
)

_EXAMPLE.fields_by_name['features'].message_type = feature__pb2._FEATURES
_SEQUENCEEXAMPLE.fields_by_name['context'].message_type = feature__pb2._FEATURES
_SEQUENCEEXAMPLE.fields_by_name['feature_lists'].message_type = feature__pb2._FEATURELISTS
DESCRIPTOR.message_types_by_name['Example'] = _EXAMPLE
DESCRIPTOR.message_types_by_name['SequenceExample'] = _SEQUENCEEXAMPLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Example = _reflection.GeneratedProtocolMessageType('Example', (_message.Message,), {
  'DESCRIPTOR': _EXAMPLE,
  '__module__': 'example_pb2'
  # @@protoc_insertion_point(class_scope:face.Example)
  })
_sym_db.RegisterMessage(Example)

SequenceExample = _reflection.GeneratedProtocolMessageType('SequenceExample', (_message.Message,), {
  'DESCRIPTOR': _SEQUENCEEXAMPLE,
  '__module__': 'example_pb2'
  # @@protoc_insertion_point(class_scope:face.SequenceExample)
  })
_sym_db.RegisterMessage(SequenceExample)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
